"use server";

import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

export interface PipelineOutputs {
  product: string;
  tech: string;
  requirements: string;
  design: string;
  tasks: string;
  compliance: string;
  dockerfile: string;
  ci: string;
}

export type PipelineResult =
  | { success: true; outputs: PipelineOutputs }
  | { success: false; error: string };

async function readFileOrMock(path: string, fallback: string): Promise<string> {
  try {
    return await readFile(resolve(process.cwd(), path), "utf-8");
  } catch {
    return fallback;
  }
}

export async function runPipeline(): Promise<PipelineResult> {
  try {
    const outputs: PipelineOutputs = {
      product: await readFileOrMock(".kiro/steering/product.md", MOCK_PRODUCT),
      tech: await readFileOrMock(".kiro/steering/tech.md", ""),
      requirements: await readFileOrMock(".kiro/specs/requirements.md", ""),
      design: await readFileOrMock(".kiro/specs/design.md", ""),
      tasks: await readFileOrMock(".kiro/specs/tasks.md", ""),
      compliance: await readFileOrMock(
        ".kiro/specs/compliance.md",
        MOCK_COMPLIANCE,
      ),
      dockerfile: await readFileOrMock("Dockerfile", MOCK_DOCKERFILE),
      ci: await readFileOrMock(".github/workflows/ci.yml", MOCK_CI),
    };

    return { success: true, outputs };
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Unknown error occurred";
    return { success: false, error: message };
  }
}

// --- Fallback mocks for agents that may not have generated files yet ---

const MOCK_PRODUCT = `# Product Strategy — KiroSpec Studio

## Executive Summary

KiroSpec Studio is an AI-powered platform that converts informal product ideas into
structured, validated architecture specifications ready for implementation.

## Problem & Solution

- **Problem:** Engineering teams spend weeks translating product ideas into actionable specs
- **Solution:** 4-agent AI pipeline that generates complete specs in seconds
- **Target Market:** Software development teams (10-500 engineers)

## Feasibility Scorecard

| Dimension | Score | Justification |
|-----------|:---:|---------------|
| Viability | 8 | Strong demand for AI dev tools |
| Desirability | 9 | Massive time savings |
| Feasibility | 7 | LLM APIs + structured output |
| **Overall** | **8** | GO |

## Verdict

**GO** — Strong market demand, technically feasible with current LLM capabilities.

## Handoff Notes for Agent 2

- **Stack direction:** Next.js, TypeScript, Vercel AI SDK
- **Budget:** MVP under $50/month
- **Key constraint:** Must work offline with mock data for demos
`;

const MOCK_COMPLIANCE = `# Compliance & Legal Audit — KiroSpec Studio

## Executive Summary

**Overall risk level:** Low
**Blocking issues:** 0
**Immediate action required:** No

## Key Findings

- All production dependencies use permissive licenses (MIT, Apache-2.0)
- No personal user data collected in MVP (demo mode only)
- AI prompts contain project descriptions only — no PII

## Open Source License Summary

| Package | License | Risk |
|---------|---------|------|
| next | MIT | 🟢 Low |
| react | MIT | 🟢 Low |
| zod | MIT | 🟢 Low |
| ai (Vercel) | Apache-2.0 | 🟢 Low |
| @ai-sdk/openai | Apache-2.0 | 🟢 Low |

## Regulatory Flags

- AI data processing — prompts contain product descriptions (non-PII)
- No user accounts in MVP — GDPR/CCPA not triggered at current scope
- Cross-border: Vercel Edge + OpenAI US — document in privacy policy at scale

## Recommendation

Proceed with MVP launch. Add privacy policy before collecting user data.

> This is an AI-generated reference guide. It does not replace professional legal advice.
`;

const MOCK_DOCKERFILE = `# Multi-stage build for KiroSpec Studio
# Generated by Agent 4 (DevSecOps)

FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --only=production

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000

HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1

CMD ["node", "server.js"]
`;

const MOCK_CI = `# CI/CD Pipeline for KiroSpec Studio
# Generated by Agent 4 (DevSecOps)

name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx tsc --noEmit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm test

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx audit-ci --high

  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx license-checker --onlyAllow 'MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause'

  build:
    needs: [lint, typecheck, test, security, license-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build
`;
